os: linux
arch:
  - arm64
  
sudo: false
language: python
python:
  - "3.7"

services:
  - xvfb

before_install:
  - sudo apt-get install graphviz

install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable bikeshed

script:
  - ./gradlew build
  - mvn verify

env:
  global:
  - ENCRYPTION_LABEL: "62536e021d06"
  - COMMIT_AUTHOR_EMAIL: "melaasar@gmail.com"
  
before_deploy:
  - export JAR_FILE=$(ls */build/libs/oml-server\-*.jar)
  
deploy:
  - provider: releases
    api_key:
      secure: mjAqI/wiZgLJ7X7ccmoniHOlMCkZESz9vSbv1cC48+egbRUihSHADVX8veNW9NGeY+795Tvlba5SlzbjGyz9yIeJdlcKlz3CqJX+a6IoONHGP+Gykm+wxLgY7Yner7k0K3ZYGBlmt+8J/uoswjhpyOS3d6zOVgTGTULJoPBBRHyqjbIPNWHG+rEhnSBisq9ypuNX4i5jh371lfvdZ6t106WJnXNbf2/HHokSvVRGf4e/be+sthhRfCIXuSjGPOPheoeD2LTMeMtFilQmSsYwrhH82ZjvZoganUM1InwGd1nMp23Nyytl1qVT6F4XpGiacSkirxx6Wbqd1eVSKxZCU/7b9v4GdNX9vzZQFscJ+xdT4HTB4RjeGqmdFGThUETh800A11jDHdqQVcto0jIs5vIo7bIEMe4zwDuLhv+/X6HEp4BMaE63QuxmrhQVCmM4QQBt0NVb3KyON+zAq8D03Z4heaaxFvruyUCkUmRvFbyNE7PDBHo9KAqY7fdTB7ieoKqlhI6478dtUbY46QlUW7YK7qQULc81CpqDC4GhFEZ1i6IzezhPJmIdiIQwT+Gno/8AIGcbp5QWnnCExVRzyzXL/CN6X3S4z5EvXFpVzf3kyZQRpYdqSWD/z0hGfffoDy+nwTTxKYwNxJsZZOET5C5zhzEbFaj+QdpKtyqxDcI=
    file_glob: true
    file: "${JAR_FILE}"
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: ./gradlew publish
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: io.opencaesar.oml.repository/deploy.sh
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: io.opencaesar.oml.specification/deploy.sh
    skip_cleanup: true
    on:
      branch: master